### ISSUE TITLE
Unable to Compress Rubber Ball of EMT in GT Compressor 

### ISSUE THREAD

**Issue by TechnicianFreak** [Dream-Master/Mods-Get-Gregged#16]
https://github.com/Dream-Master/Mods-Get-Gregged/blob/af4efd950c015fc51b50d65a3810d5b25494eacb/Custom-Modpack-Scripts/GTNewHorizons/scripts/Emt.zs#L9

https://github.com/Dream-Master/Mods-Get-Gregged/blob/af4efd950c015fc51b50d65a3810d5b25494eacb/Custom-Modpack-Scripts/GTNewHorizons/scripts/Emt.zs#L1207

It looks like I should compress them in IC2 Compressor?But obviously I can't craft this machine.

**Comment by Dream-Master** [comment]
GT Tweaker using old ic2 compressor. Open up an issue on my GT Tweaker repo. Maybe we get a fix.
