### ISSUE TITLE
Pull request then ownership transfer

### ISSUE THREAD

**Issue by elifoster** [Dream-Master/Mods-Get-Gregged#27]
@Dream-Master 
Could you submit a pull request to my repository Mods-Get-Gregged. Once you do that, and all merge conflicts are handled, I will accept the merge, then transfer the ownership of that repository to you.

**Comment by Dream-Master** [comment]
Ok I can do when I come back from work.

**Comment by Dream-Master** [comment]
Ok Pull Request done.

**Comment by elifoster** [comment]
Will transfer ownership when I can use a computer. Please don't push to this, and instead push to the base repository (elifoster/mods-get-gregged) until ownership is transferred.

**Comment by Dream-Master** [comment]
ok

**Comment by elifoster** [comment]
Okay so you have to delete this repository before you can get it transferred.

**Comment by Dream-Master** [comment]
Ok how i can do this?

**Comment by elifoster** [comment]
You have to delete the forked repository because it is in the same network as my repository. You can't fork your own repositories.
